# Generated by Django 3.0.6 on 2020-06-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_selectedtheme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
