# Generated by Django 3.0.6 on 2020-06-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200608_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedTheme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
