# Generated by Django 3.0.6 on 2020-05-26 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import makeportfolio.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('user', models.OneToOneField(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('link', models.URLField()),
                ('photo', models.ImageField(upload_to='work_photo/')),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_name', models.CharField(max_length=120)),
                ('client_review', models.DecimalField(decimal_places=1, max_digits=3)),
                ('client_feedback', models.TextField()),
                ('user', models.OneToOneField(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.WorkCategory')),
            ],
        ),
    ]
