# Generated by Django 3.0.6 on 2020-05-24 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import makeportfolio.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=220, unique=True)),
                ('board', models.CharField(max_length=120)),
                ('institute', models.CharField(max_length=220)),
                ('passing_year', models.CharField(max_length=4)),
                ('result', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
