# Generated by Django 3.0.6 on 2020-05-28 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_auto_20200528_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('user', 'degree')},
        ),
    ]
