# Generated by Django 3.0.6 on 2020-06-12 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import makeportfolio.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_remove_profile_about'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('persent', models.IntegerField()),
                ('user', models.ForeignKey(default=makeportfolio.helper.get_user_profile, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=220)),
                ('user', models.ForeignKey(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('client_name', models.CharField(max_length=120)),
                ('client_review', models.DecimalField(decimal_places=1, max_digits=3)),
                ('client_feedback', models.TextField()),
                ('budjet', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=120)),
                ('preview', models.URLField()),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_item.PortfolioCategory')),
                ('user', models.ForeignKey(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=220)),
                ('job_context', models.TextField()),
                ('company_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(default=makeportfolio.helper.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('about', models.TextField()),
                ('resume', models.FileField(upload_to='resume/')),
                ('user', models.OneToOneField(default=makeportfolio.helper.get_user_profile, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=220)),
                ('board', models.CharField(max_length=120)),
                ('institute', models.CharField(max_length=220)),
                ('passing_year', models.CharField(max_length=4)),
                ('result', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(default=makeportfolio.helper.get_user_profile, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
            options={
                'unique_together': {('profile', 'degree')},
            },
        ),
    ]
