# Generated by Django 3.0.6 on 2020-06-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='profile',
        ),
    ]
