# Generated by Django 3.0.6 on 2020-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_item', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('about', models.TextField()),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('client', models.CharField(max_length=120)),
                ('budjet', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=120)),
                ('preview', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=220)),
            ],
        ),
    ]
