# Generated by Django 3.0.6 on 2020-06-12 11:26

from django.db import migrations, models
import django.db.models.deletion
import makeportfolio.helper


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_about'),
        ('portfolio_item', '0005_auto_20200612_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(default=makeportfolio.helper.get_user_profile, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
