# Generated by Django 3.0.6 on 2020-06-13 10:32

from django.db import migrations, models
import django.db.models.deletion
import makeportfolio.helper


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('portfolio_item', '0005_auto_20200613_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.PositiveIntegerField()),
                ('clients', models.PositiveIntegerField()),
                ('partners', models.PositiveIntegerField()),
                ('cup_of_coffee', models.PositiveIntegerField()),
                ('profile', models.OneToOneField(default=makeportfolio.helper.get_user_profile, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
