# Generated by Django 3.0.6 on 2020-06-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_theme_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtheme',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theme.Theme'),
            preserve_default=False,
        ),
    ]
